language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer install --prefer-source --no-interaction --no-dev
  - touch app/database/production.sqlite
  - php artisan migrate --env=testing